### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by Carly-Schaaf** [burnwatt/kidplex#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [ ] Has working demo login
- [ ] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [ ] The site should look exactly like the actual site
- [ ] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by Carly-Schaaf** [comment]
Looking good, Josh! Just a few things: 

- [ ] Something is up with your demo user login. I am able to sign in as a demo user, but looking at the console shows that every time the demo user logs in, you're getting "Incorrect email/password" errors in your redux state. When the demo login takes a bit to process, these errors actually show up on the page.
- [ ] Your sign in/demo login/sign up buttons should have `cursor: pointer` on hover
- [ ] You need to add a bit of styling to your errors. They should be a bit smaller and have some padding so that they're not so scrunched up against the input boxes.
- [ ] Your "Join Free For a Month" button needs some top margin so that it's not so scrunched up against the "WATCH ANYTIME. CANCEL ANYTIME"

Keep up the great work!!

**Comment by burnwatt** [comment]
Hey Carly!

I've updated the site to reflect your edits. Please note that the orange styling on the session errors is what Netflix decided to use...
